### ISSUE TITLE
Open badges Integration

### ISSUE THREAD

**Issue by nicokant94** [Mte90/DaTask#21]
Each task completed could be linked to a specific Open Badge, for example: https://wordpress.org/plugins/wpbadger/
(this project isn't maintained, but we can contact the developer)

**Comment by Mte90** [comment]
I've integrated BadgeOS plugin that is the system in wordpress for the badge that have many addons.
With that with cred.ly is possible share to mozilla backpack or with another plugin directly to mozilla backpack.
