### ISSUE TITLE
Grammar check

### ISSUE THREAD

**Issue by buluma** [Mte90/DaTask#34]
Hi Daniele

I'm not sure if this is deliberate but i noticed the use of "Open an issues" instead of "Open an issue"

http://datask.mte90.net/task/open-an-issues/

**Comment by Mte90** [comment]
Is a demo task but yes is a typo

**Comment by buluma** [comment]
aah alright.

That makes sense then.
Thanks for explaining.

On Sun, Jul 12, 2015 at 7:22 PM, Daniele Scasciafratte <
notifications@github.com> wrote:

> Is a demo task but yes is a typo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mte90/DaTask/issues/34#issuecomment-120738204>.
>



-- 
</Michael Buluma>
