### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by nicokant94** [Mte90/DaTask#37]
after my login with persona the page gets into an infinite loop. 

![schermata da 2015-07-22 19-54-02](https://cloud.githubusercontent.com/assets/6927678/8832810/6bca5eb2-30ab-11e5-9b6f-330966f554e4.png)

**Comment by Mte90** [comment]
You've already an account on the site?

**Comment by nicokant94** [comment]
no, but I supposed that using Persona login a wouldn't have required an already registered account

**Comment by nicokant94** [comment]
I have still open the loop page, are there some pieces of information I can get to help you?

**Comment by Mte90** [comment]
is a mozilla persona plugin bug, i thnk that require a debug or alert.
Maybe is better open a ticket in this plugin
