### ISSUE TITLE
api rest

### ISSUE THREAD

**Issue by nicokant94** [Mte90/DaTask#49]
a rest interface would be useful to cooperate with other projects. 
In particular it should have: 
- Get user completed task
- Mark task as completed

I'd like to make interact projects as WebCompat and Firefox Milano website with passopasso

**Comment by Mte90** [comment]
The WordPress API add the support but i can add the support for fields of the plugin

**Comment by Mte90** [comment]
The WordPress API supports everything is missing only the content because the plugin use many fields.
I've created a wiki page with few info https://github.com/Mte90/DaTask/wiki/API-Rest-V1

**Comment by Mte90** [comment]
THe api actually show only the data, for add the support for logging, mark etc is not in the actually roadmap.
