### ISSUE TITLE
DaTask will not allow deletion

### ISSUE THREAD

**Issue by idshealth** [Mte90/DaTask#72]
After installing it on my WP site, I decided to deactivate and delete it. Many attempts to delete have resulted in a "500" error.  I don't have any problems with any other plugin.

**Comment by Mte90** [comment]
to remove you are using the uninstall system of wordpress or removing the folder of the plugin manually?

**Comment by idshealth** [comment]
I am using the wordpress uninstall system.

**Comment by Mte90** [comment]
I fixed the problem, asap will be released a new version that fix that problem

**Comment by idshealth** [comment]
Got it.

Perfect.

Thanks,
Rich
